import json
json_output = {
  'response_code': 1,
  'total': 71,
  'scan_id': '9d116b1b0c1200ca75016e4c010bc94836366881b021a658ea7f8548b6543c1e-1571420264',
  'verbose_msg': 'Scan finished, scan information embedded in this object',
  'filescan_id': None,
  'url': 'https://google.com/',
  'positives': 0,
  'resource': 'https://google.com',
  'scans': {
    'Phishtank': {'result': 'clean site', 'detected': False},
    'Baidu-International': {'result': 'clean site', 'detected': False},
    'Spamhaus': {'result': 'clean site', 'detected': False},
    'ThreatHive': {'result': 'clean site', 'detected': False},
    'Netcraft': {'result': 'unrated site', 'detected': False},
    'CLEAN MX': {'result': 'clean site', 'detected': False},
    'ZeusTracker': {'result': 'clean site', 'detail': 'https://zeustracker.abuse.ch/monitor.php?host=google.com', 'detected': False},
    'CyRadar': {'result': 'clean site', 'detected': False}, 'URLQuery': {'result': 'clean site', 'detected': False},
    'Antiy-AVL': {'result': 'clean site', 'detected': False},
    'OpenPhish': {'result': 'clean site', 'detected': False},
    'AegisLab WebGuard': {'result': 'clean site', 'detected': False},
    'MalwarePatrol': {'result': 'clean site', 'detected': False},
    'ADMINUSLabs': {'result': 'clean site', 'detected': False},
    'ZeroCERT': {'result': 'clean site', 'detected': False},
    'Yandex Safebrowsing': {'result': 'clean site', 'detail': 'http://yandex.com/infected?l10n=en&url=https://google.com/', 'detected': False},
    'CyberCrime': {'result': 'clean site', 'detected': False},
    'ESTsecurity-Threat Inside': {'result': 'clean site', 'detected': False},
    'securolytics': {'result': 'clean site', 'detected': False},
    'malwares.com URL checker': {'result': 'clean site', 'detected': False},
    'Spam404': {'result': 'clean site', 'detected': False},
    'Emsisoft': {'result': 'clean site', 'detected': False},
    'Comodo Site Inspector': {'result': 'clean site', 'detected': False},
    'SCUMWARE.org': {'result': 'clean site', 'detected': False},
    'Sophos': {'result': 'unrated site', 'detected': False},
    'Kaspersky': {'result': 'clean site', 'detected': False},
    'SecureBrain': {'result': 'clean site', 'detected': False},
    'VX Vault': {'result': 'clean site', 'detected': False},
    'Tencent': {'result': 'clean site', 'detected': False},
    'EonScope': {'result': 'clean site', 'detected': False},
    'BADWARE.INFO': {'result': 'clean site', 'detected': False},
    'ZDB Zeus': {'result': 'clean site', 'detected': False},
    'K7AntiVirus': {'result': 'clean site', 'detected': False},
    'BitDefender': {'result': 'clean site', 'detected': False},
    'Malc0de Database': {'result': 'clean site', 'detail': 'http://malc0de.com/database/index.php?search=google.com', 'detected': False},
    'Nucleon': {'result': 'clean site', 'detected': False},
    'Fortinet': {'result': 'clean site', 'detected': False},
    'Malwarebytes hpHosts': {'result': 'clean site', 'detected': False},
    'Google Safebrowsing': {'result': 'clean site', 'detected': False},
    'Web Security Guard': {'result': 'clean site', 'detected': False},
    'Avira': {'result': 'clean site', 'detected': False},
    'Trustwave': {'result': 'clean site', 'detected': False},
    'ZCloudsec': {'result': 'clean site', 'detected': False},
    'FraudScore': {'result': 'clean site', 'detected': False},
    'Malware Domain Blocklist': {'result': 'clean site', 'detected': False},
    'Virusdie External Site Scan': {'result': 'clean site', 'detected': False},
    'Zerofox': {'result': 'clean site', 'detected': False},
    'URLhaus': {'result': 'clean site', 'detected': False},
    'CRDF': {'result': 'clean site', 'detected': False},
    'zvelo': {'result': 'clean site', 'detected': False},
    'DNS8': {'result': 'clean site', 'detected': False},
    'AlienVault': {'result': 'clean site', 'detected': False},
    'StopBadware': {'result': 'unrated site', 'detected': False},
    'Sucuri SiteCheck': {'result': 'clean site', 'detected': False},
    'Malekal': {'result': 'clean site', 'detected': False},
    'AutoShun': {'result': 'unrated site', 'detected': False},
    'MalwareDomainList': {'result': 'clean site', 'detail': 'http://www.malwaredomainlist.com/mdl.php?search=google.com', 'detected': False},
    'Opera': {'result': 'clean site', 'detected': False},
    'Segasec': {'result': 'unrated site', 'detected': False},
    'Forcepoint ThreatSeeker': {'result': 'clean site', 'detected': False},
    'Dr.Web': {'result': 'clean site', 'detected': False},
    'NotMining': {'result': 'unrated site', 'detected': False},
    'Quttera': {'result': 'clean site', 'detected': False},
    'FraudSense': {'result': 'clean site', 'detected': False},
    'Malwared': {'result': 'clean site', 'detected': False},
    'Rising': {'result': 'clean site', 'detected': False},
    'PhishLabs': {'result': 'unrated site', 'detected': False},
    'ESET': {'result': 'clean site', 'detected': False},
    'Blueliv': {'result': 'clean site', 'detected': False},
    'desenmascara.me': {'result': 'clean site', 'detected': False},
    'G-Data': {'result': 'clean site', 'detected': False}
    },
    'permalink': 'https://www.virustotal.com/url/9d116b1b0c1200ca75016e4c010bc94836366881b021a658ea7f8548b6543c1e/analysis/1571420264/', 'scan_date': '2019-10-18 17:37:44'}
#json_dict = json.loads(json_output)

json_dict = json.dumps(json_output['url'])
json_dict1 = json.dumps(json_output['positives'])
json_output_list = [json_dict,json_dict1]

Actual_list = []
Actual_list.append(json_output_list)

for each_item in Actual_list:
    print(each_item)
